#!/usr/bin/env python3
"""Generate the bit-exact golden fixtures for the C++ BBS port test.

Runs the reference Python ``branch_and_bound_candidates`` on a set of
deterministic fixtures (varying map, scan, yaw count, pyramid depth, top-K and
NMS) and emits ``test/bbs_golden_fixtures.inc`` -- a C++ header literal of the
inputs and the resulting candidate tuples. ``test_bbs_branch_and_bound.cpp``
includes it and asserts the C++ port reproduces every tuple exactly.

This is the machine-independent half of the G2 BBS C++ port verification
(docs/g2_bbs_speedup.md): the golden is frozen from Python, so the C++ port is
proven bit-exact without an idle machine; only the wall-clock speed claim needs
one. Re-run after any change to the Python BBS to refresh the golden.
"""

import math
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import make_bbs_relocalization_attempts as bbs  # noqa: E402


def make_map(height, width, occupied_cells):
    occ = np.zeros((height, width), dtype=bool)
    for (y, x) in occupied_cells:
        occ[y, x] = True
    return occ


def cluster_map(height, width, seed, n_clusters, cluster_size):
    rng = np.random.default_rng(seed)
    occ = np.zeros((height, width), dtype=bool)
    for _ in range(n_clusters):
        cy = int(rng.integers(2, height - 2))
        cx = int(rng.integers(2, width - 2))
        for _ in range(cluster_size):
            y = min(height - 1, max(0, cy + int(rng.integers(-2, 3))))
            x = min(width - 1, max(0, cx + int(rng.integers(-2, 3))))
            occ[y, x] = True
    return occ


def scan_from_occupied(occ, resolution_m, true_xy, radius_m, max_points, seed):
    ys, xs = np.nonzero(occ)
    wx = (xs + 0.5) * resolution_m
    wy = (ys + 0.5) * resolution_m
    d = np.hypot(wx - true_xy[0], wy - true_xy[1])
    sel = np.nonzero(d < radius_m)[0]
    rng = np.random.default_rng(seed)
    if len(sel) > max_points:
        sel = rng.choice(sel, max_points, replace=False)
    dx = wx[sel] - true_xy[0]
    dy = wy[sel] - true_xy[1]
    return np.stack([dx, dy], axis=1)


FIXTURES = []


def add(name, occ, scan, resolution_m, ares_rad, depth, max_c, nms):
    cands = bbs.branch_and_bound_candidates(
        occupancy=occ, scan_xy_m=np.asarray(scan, dtype=np.float64),
        resolution_m=resolution_m, angular_resolution_rad=ares_rad,
        pyramid_depth=depth, max_candidates=max_c, nms_radius_cells=nms)
    FIXTURES.append(dict(
        name=name, occ=occ, scan=np.asarray(scan, dtype=np.float64),
        resolution_m=resolution_m, ares_rad=ares_rad, depth=depth,
        max_c=max_c, nms=nms, cands=cands))


# F1: the Python unit-test fixture (single yaw, top-K ordering).
add("six_by_six_single_yaw",
    make_map(6, 6, [(2, 2), (2, 3), (4, 4)]),
    [[0.0, 0.0], [1.0, 0.0]],
    1.0, 2.0 * math.pi, 2, 5, 0)

# F2: medium clustered map, 4 yaws, no NMS.
occ2 = cluster_map(40, 48, seed=1, n_clusters=6, cluster_size=12)
scan2 = scan_from_occupied(occ2, 1.0, (24.0, 20.0), 12.0, 60, seed=2)
add("medium_4yaw_no_nms", occ2, scan2, 1.0, math.radians(90.0), 3, 8, 0)

# F3: same map/scan with NMS, 8 yaws.
add("medium_8yaw_nms3", occ2, scan2, 1.0, math.radians(45.0), 3, 8, 3)

# F4: larger map, finer yaw, deeper pyramid, NMS.
occ4 = cluster_map(64, 64, seed=7, n_clusters=10, cluster_size=16)
scan4 = scan_from_occupied(occ4, 0.5, (16.0, 16.0), 10.0, 80, seed=8)
add("large_12yaw_depth4_nms2", occ4, scan4, 0.5, math.radians(30.0), 4, 10, 2)


def grid_literal(occ):
    h, w = occ.shape
    flat = "".join("1" if occ[y, x] else "0" for y in range(h) for x in range(w))
    return h, w, flat


def emit(out_path):
    lines = []
    lines.append("// AUTO-GENERATED by scripts/generate_bbs_golden_fixtures.py -- do not edit.")
    lines.append("// Bit-exact golden output of the Python branch_and_bound_candidates,")
    lines.append("// frozen so the C++ port (bbs_branch_and_bound.hpp) is verifiable offline.")
    lines.append("#include <array>")
    lines.append("#include <string>")
    lines.append("#include <vector>")
    lines.append("")
    lines.append("struct GoldenCandidate { int tx; int ty; int yaw_index; int hit; };")
    lines.append("struct GoldenFixture {")
    lines.append("  const char* name;")
    lines.append("  int height; int width; std::string occ;  // row-major '0'/'1'")
    lines.append("  std::vector<std::array<double,2>> scan;")
    lines.append("  double resolution_m; double ares_rad; int depth; int max_c; int nms;")
    lines.append("  std::vector<GoldenCandidate> expected;")
    lines.append("};")
    lines.append("")
    lines.append("inline std::vector<GoldenFixture> golden_fixtures() {")
    lines.append("  std::vector<GoldenFixture> f;")
    for fx in FIXTURES:
        h, w, flat = grid_literal(fx["occ"])
        lines.append("  {")
        lines.append("    GoldenFixture g;")
        lines.append(f'    g.name = "{fx["name"]}";')
        lines.append(f"    g.height = {h}; g.width = {w};")
        lines.append(f'    g.occ = "{flat}";')
        scan_items = ", ".join(
            f"{{{float(x[0])!r}, {float(x[1])!r}}}" for x in fx["scan"])
        lines.append(f"    g.scan = {{{scan_items}}};")
        lines.append(
            f"    g.resolution_m = {fx['resolution_m']!r}; g.ares_rad = {fx['ares_rad']!r};")
        lines.append(
            f"    g.depth = {fx['depth']}; g.max_c = {fx['max_c']}; g.nms = {fx['nms']};")
        exp = ", ".join(
            f"{{{c.tx_cell}, {c.ty_cell}, {c.yaw_index}, {c.hit_count}}}"
            for c in fx["cands"])
        lines.append(f"    g.expected = {{{exp}}};")
        lines.append("    f.push_back(g);")
        lines.append("  }")
    lines.append("  return f;")
    lines.append("}")
    out_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_path} with {len(FIXTURES)} fixtures")
    for fx in FIXTURES:
        print(f"  {fx['name']}: {len(fx['cands'])} candidates, "
              f"top hit={fx['cands'][0].hit_count if fx['cands'] else 0}")


if __name__ == "__main__":
    emit(ROOT / "test" / "bbs_golden_fixtures.inc")
